import { Template } from './types';

export const templates: Template[] = [
  {
    id: 1,
    name: 'Minima Colored',
    description: 'A clean, minimal theme perfect for personal blogs and writers who want to focus on content.',
    thumbnailUrl: 'https://i.imgur.com/O12lT8j.png',
    previewUrl: 'https://gooyaabitemplates.com/soramini-blogger-templates/',
    downloadUrl: 'https://gooyaabitemplates.com/soramini-blogger-templates/',
    isPremium: false,
    features: ['Responsive', 'SEO Friendly', 'Minimal Design', 'Fast Loading'],
    tags: ['Minimal', 'Personal'],
    author: 'Gooyabi',
  },
  {
    id: 2,
    name: 'MagPro',
    description: 'A professional magazine-style theme with a grid layout, ideal for news sites and content-heavy blogs.',
    thumbnailUrl: 'https://i.imgur.com/W2C07R2.png',
    previewUrl: 'https://gooyaabitemplates.com/flexmag-blogger-template/',
    downloadUrl: 'https://gooyaabitemplates.com/flexmag-blogger-template/',
    isPremium: true,
    features: ['Responsive', 'AdSense Ready', 'Custom Widgets', 'Mega Menu'],
    tags: ['Magazine', 'News'],
    author: 'Templateify',
  },
  {
    id: 3,
    name: 'Folio',
    description: 'A sleek and modern portfolio theme to showcase your creative work, photos, or projects.',
    thumbnailUrl: 'https://i.imgur.com/gfh5fE1.png',
    previewUrl: 'https://gooyaabitemplates.com/folio-blogger-template/',
    downloadUrl: 'https://gooyaabitemplates.com/folio-blogger-template/',
    isPremium: false,
    features: ['Responsive', 'Portfolio Grid', 'Dark Mode', 'Contact Form'],
    tags: ['Portfolio', 'Personal'],
    author: 'Odd Themes',
  },
  {
    id: 4,
    name: 'E-commerce Pro',
    description: 'A feature-rich template for setting up an online store on Blogger. Includes a cart and product pages.',
    thumbnailUrl: 'https://i.imgur.com/8h7g8hA.png',
    previewUrl: 'https://gooyaabitemplates.com/sora-cart-blogger-templates/',
    downloadUrl: 'https://gooyaabitemplates.com/sora-cart-blogger-templates/',
    isPremium: true,
    features: ['E-commerce Ready', 'Responsive', 'Product Grid', 'Payment Integration'],
    tags: ['E-commerce', 'Portfolio'],
    author: 'Sora Templates',
  },
   {
    id: 5,
    name: 'Sora News',
    description: 'A clean and modern news theme with multiple layout options and a professional design.',
    thumbnailUrl: 'https://i.imgur.com/5N0b0E5.png',
    previewUrl: 'https://gooyaabitemplates.com/sora-news-blogger-template/',
    downloadUrl: 'https://gooyaabitemplates.com/sora-news-blogger-template/',
    isPremium: false,
    features: ['Responsive', 'SEO Friendly', 'Multiple Layouts', 'Customizable'],
    tags: ['News', 'Magazine'],
    author: 'Sora Templates',
  },
  {
    id: 6,
    name: 'Persona',
    description: 'A stylish personal blog theme with a focus on typography and beautiful imagery.',
    thumbnailUrl: 'https://i.imgur.com/Q6X5L3p.png',
    previewUrl: 'https://gooyaabitemplates.com/persona-blogger-template/',
    downloadUrl: 'https://gooyaabitemplates.com/persona-blogger-template/',
    isPremium: true,
    features: ['Responsive', 'Elegant Design', 'Google Fonts', 'SEO Friendly'],
    tags: ['Personal', 'Minimal'],
    author: 'Templateism',
  },
];
